services:
  3xui:
    image: rujhan/3x-ui:latest
    container_name: 3xui_app
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - $PWD/db/:/etc/x-ui/
      - $PWD/cert/:/root/cert/
    labels:
      - traefik.enable=true

      # Hostname
      - traefik.http.routers.3xui.rule=Host(`3x.ruju.qzz.io`)

      #test
      # - traefik.http.routers.3xui.rule=Host(`localhost`)

      # HTTPS only
      - traefik.http.routers.3xui.entrypoints=websecure

      # TLS
      - traefik.http.routers.3xui.tls=true
      - traefik.http.routers.3xui.tls.certresolver=letsencrypt

      #test
      # - traefik.http.routers.3xui.entrypoints=web

      # network
      - traefik.docker.network=traefikproxy

      # Internal 3x-ui port
      - traefik.http.services.3xui.loadbalancer.server.port=2053
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      XUI_ENABLE_FAIL2BAN: "true"
      XUI_INIT_WEB_BASE_PATH: "/"

    tty: true
    expose:
      - "2053"
    networks:
      - traefikproxy
    restart: unless-stopped

  # Reverse proxy settup
  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: unless-stopped
    command:
      # - --api.dashboard=true # to be commended in production
      # - --api.insecure=true # to be commended in production
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false

     

      # HTTP
      - --entrypoints.web.address=:80

      # HTTPS
      - --entrypoints.websecure.address=:443

      # Let's Encrypt
      - --certificatesresolvers.letsencrypt.acme.email=rujhanbheem123@gmail.com
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      

    ports:
      - "80:80"
      - "443:443"
      # - "8080:8080" # to be commended in production
    networks:
      - traefikproxy

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt


networks:
  traefikproxy:
    name: traefikproxy